# vim: ft=nginx

server {
    listen 80;
    listen 443 ssl;

    server_name claw.lipbcu.love;

    ssl_certificate /etc/letsencrypt/live/lipbcu.love/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lipbcu.love/privkey.pem;

    location / {
		proxy_pass http://claw-openclaw-gateway-1:18789;

        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeout settings for long-lived connections
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
